<?php

namespace App\Domain\Repositories;

use App\Domain\Entities\Book;

class BookRepository extends AbstractRepository
{
    protected $model;
    
    /**
     * BookRepository constructor.
     * @param Book $book
     */
    public function __construct(Book $book)
    {
        $this->model = $book;
    }
    
    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
    
    public function getById($id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }
    
    public function getByField($att, $field)
    {
        return parent::getByField($att, $field); // TODO: Change the autogenerated stub
    }
    
    public function paginate($limit, $key, $search)
    {
        return parent::paginate($limit, $key, $search); // TODO: Change the autogenerated stub
    }
    
    public function created($cover, array $data)
    {
        return parent::create([
            'judul'        => e($data['judul']),
            'pengarang'    => e($data['pengarang']),
            'penerbit'     => e($data['penerbit']),
            'tahun_terbit' => e($data['tahun_terbit']),
            'jumlah_buku'  => e($data['jumlah_buku']),
            'deskripsi'    => e($data['deskripsi']),
            'cover'        => $cover
        ]);
    }
    
    
    public function updated($id, array $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }
    
    
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
