<?php
/**
 * Created by PhpStorm.
 * User: FERDY
 * Date: 12/16/2018
 * Time: 3:28 AM
 */

namespace App\Domain\Repositories;


use App\Domain\Entities\Transaction;

class TransactionRepository extends AbstractRepository
{
    protected $model;
    
    /**
     * TransactionRepository constructor.
     * @param $model
     */
    public function __construct(Transaction $model)
    {
        $this->model = $model;
    }
    
    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
    
    public function getById($id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }
    
    public function getByField($att, $field)
    {
        return parent::getByField($att, $field); // TODO: Change the autogenerated stub
    }
    
    public function paginate($limit, $key, $search)
    {
        return parent::paginate($limit, $key, $search); // TODO: Change the autogenerated stub
    }
    
    public function create(array $data)
    {
        return parent::create([
            'kd_transaksi' => e($data['kode_transaksi']),
            'tgl_pinjam'   => e($data['tgl_pinjam']),
            'tgl_kembali'  => e($data['tgl_kembali']),
            'book_id'      => e($data['buku_id']),
            'member_id'    => e($data['anggota_id']),
            'ket'          => e($data['ket']),
            'status'       => 'pinjam'
        ]);
    }
    
    public function update($id, array $attributes)
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }
    
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
    
    
}